/**
 * @description       : 
 * @author            : Anil Mannem
 * @last modified on  : 04-06-2021
 * @last modified by  : Anil Mannem
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   04-06-2021   Anil Mannem   Initial Version
**/
public with sharing class DemoUday {
    /**
    * @description 
    * @author Anil Mannem | 04-06-2021 
    **/
    public DemoUday() {

        //This is a coment
    }
}