/**
 * @description Test Class for Omni_ManagerTreeSchedule.
 * @author      Anil Mannem
 * @date        25-Jan-2021
 */
@isTest
public class Omni_ManagerTreeScheduleTest {
    // @isTest
    // static void testSchedule(){
    //     Test.startTest();
    //     Omni_ManagerTreeSchedule omts = new Omni_ManagerTreeSchedule();
    //     String sch = '0 1 * * * ?';
    //     String jobID = System.schedule('Schedule for Manager Tree Batch Job', sch, omts);
    //     Test.stopTest();
    // }
}